#!/bin/bash
apt update -y
apt install -y apache2

systemctl start apache2
systemctl enable apache2

mkdir -p /var/www/html
echo "<h1>Welcome to tech-verse academy</h1>" > /var/www/html/index.html
echo "<p>This file is created automatically at boot time.</p>" >> /var/www/html/index.html
